FROM alpine:3.20

RUN apk add --no-cache libgcc ffmpeg openssl ca-certificates \
    && addgroup -S appgroup && adduser -S appuser -G appgroup \
    && mkdir -p /app/bucket && chown -R appuser:appgroup /app

WORKDIR /app
COPY fragrans /usr/local/bin/fragrans
RUN chmod +x /usr/local/bin/fragrans

ARG VERSION
ARG GIT_REVISION
ENV APP_VERSION=${VERSION} \
    GIT_REVISION=${GIT_REVISION}

USER appuser
EXPOSE 3821
CMD ["fragrans"]
